# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180715_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='hasAnagram',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
