# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 02:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_word_hasanagram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='letters',
            field=models.CharField(max_length=4),
        ),
    ]
