# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-16 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180716_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='length',
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=4, primary_key=True, serialize=False),
        ),
    ]
